# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 1
  end

  boxes = [
    { :name => "nginx1", :ip => "192.168.42.2" },
    { :name => "nginx2", :ip => "192.168.42.3" },
  ]

  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network :private_network, ip: opts[:ip]
    end
  end
end
