---
# setup logrotate
- hosts: logrotate
  become: true

  vars:

  roles:
  - role: SimpliField.logrotate
    logrotate_applications:
    - name: apt
      definitions:
      - logs:
        - /var/log/apt/term.log
        - /var/log/apt/history.log
        options:
          - rotate 12
          - monthly
          - missingok
          - notifempty
          - compress
