---
# Build 2.6 replicaset
- hosts: mongo
  become: True

  roles:
    - SimpliField.mongo
    - SimpliField.mongo-replica-set
    - SimpliField.network-hosts

- hosts: mongo1
  become: true

  roles:
    - SimpliField.mongo-replica-set

  tasks:
    - mongodb_replica_set: state="{{mongo_replication_state | default(omit) }}"
    - mongodb_replica_set: member="mongo2" state=present
    - mongodb_replica_set: member="mongo3" state=present

    - name: download mongo dataset
      get_url:
        url: "https://raw.githubusercontent.com/mongodb/docs-assets/primer-dataset/primer-dataset.json"
        dest: "/tmp/dataset.json"
    - name: import dataset
      command: >
        mongoimport --db test --collection restaurants --drop --file /tmp/dataset.json

