---
# Upgrade to 3.0
- hosts: mongo3
  become: true

  tasks:
  - include: mongo-uninstall.yml

- hosts: mongo3
  become: true
  roles:
  - role: SimpliField.mongo
    mongodb_version: 3.0

- hosts: mongo3
  become: true
  tasks:
  - include: mongo-start.yml

# Archive old storage
- hosts: mongo3
  become: true
  tasks:
  - include: mongo-archive.yml

# Set new mongodb storage engine
- hosts: mongo3
  become: true
  roles:
  - role: SimpliField.mongo
    mongodb_version: 3.0
    mongodb_storage_engine: "wiredTiger"

- hosts: mongo3
  become: true
  tasks:
  - include: mongo-start.yml
