---
# Upgrade to 3.2
- hosts: mongo1
  become: true

  tasks:
  - include: mongo-uninstall.yml

- hosts: mongo1
  become: true
  roles:
  - role: SimpliField.mongo
    mongodb_version: 3.2

- hosts: mongo1
  become: true
  tasks:
  - include: mongo-start.yml
