---
# setup minio user & path
- hosts: minio
  become: true

  vars:

  roles:
  - role: SimpliField.users
    users:
    - miniouser:
      name: "minio"
      comment: "minio user"
      createhome: "yes"
      shell: "/bin/false"
  - role: SimpliField.path
    path: "/data-objects"
    owner: "minio"
    group: "minio"
  - role: SimpliField.path
    path: "/home/minio/.minio/certs"
    owner: "minio"
    group: "minio"
  - role: SimpliField.ssl
    ssl_path: /home/minio/.minio/certs
    ssl_path_owner: minio
    ssl_path_group: minio
    ssl_cert_self_signed: true
    ssl_privkey_path: /home/minio/.minio/certs/private.key
    ssl_cert_path: /home/minio/.minio/certs/public.crt

# setup minio
- hosts: minio
  become: true

  vars:
    minio_datadirs:
    - /data-objects
    minio_access_key: "admin"
    minio_secret_key: "adminadmin"

  roles:
  - SimpliField.minio
