---
# setup postgres
- hosts: postgres
  become: true

  vars:
    postgresql_users:
    - name: vagrant
      pass: pass
      encrypted: yes
    postgresql_databases:
    - name: vagrant
      owner: vagrant
      hstore: yes
      uuid_ossp: yes
      citext: yes
      encoding: 'UTF-8'
      lc_collate: 'en_US.UTF-8'
      lc_ctype: 'en_US.UTF-8'

  roles:
  - role: SimpliField.postgres
